### ISSUE TITLE
Multiple classes in the same file are ignored

### ISSUE THREAD

**Issue by smortvedt** [aconrad/pycobertura#112]
It looks like if a cobertura report has multiple classes in the same file, only the first class will populate the stats for that file and the others will be ignored. 
[coverageExample.zip](https://github.com/aconrad/pycobertura/files/6131849/coverageExample.zip)

**Comment by aconrad** [comment]
Thanks @smortvedt for reporting this and even submitting a pull request, this is much appreciated. 🙏

I'm out of town for a bit so I won't have much time to look at it in the coming days, but hopefully I can take a closer look next week. 👍

**Comment by aconrad** [comment]
Your changes have been picked up by @gro1m and were merged to master (I made sure you get the credit on the commit). Going to close this issue now, let me know how things work for you.
