### ISSUE TITLE
Add option to remove missing column from HtmlReporterDelta

### ISSUE THREAD

**Issue by loganharbour** [aconrad/pycobertura#115]
I propose adding an option to HtmlReporterDelta to remove the "Missing" column. We've implemented pycobetura for our coverage reports in [idaholab/moose](https://github.com/idaholab/moose) (see https://github.com/idaholab/moose/pull/18395#issuecomment-917463944 for an example). This column can get pretty huge on some of our large PRs, so we remove it manually.

I can put up a PR for this if you find it appropriate.

Also - great application, we're a huge fan. I've got some other improvements I think would be fitting for diff reports that I can add in the near future.

**Comment by aconrad** [comment]
Hey @loganharbour,

> I propose adding an option to HtmlReporterDelta to remove the "Missing" column. We've implemented pycobetura for our coverage reports in [idaholab/moose](https://github.com/idaholab/moose) (see [idaholab/moose#18395 (comment)](https://github.com/idaholab/moose/pull/18395#issuecomment-917463944) for an example). This column can get pretty huge on some of our large PRs, so we remove it manually.
> 
> I can put up a PR for this if you find it appropriate.

That sounds reasonable to me, thank you! 👍

> Also - great application, we're a huge fan. I've got some other improvements I think would be fitting for diff reports that I can add in the near future.

Thanks for your kind words, it's always appreciated and it makes me happy to know that people find my tool useful. ❤️

And yes, I'm always open to new ideas/contributions. Keep them coming! :)
