### ISSUE TITLE
Support for reading entries by row/column of 'pycobertura show' outputted table

### ISSUE THREAD

**Issue by gro1m** [aconrad/pycobertura#120]
Command:
```bash
pycobertura show coverage.xml
```
Example output:
```bash
Filename                                  Stmts    Miss  Cover    Missing
--------------------------------------  -------  ------  -------  ---------
src/__init__.py                               0       0  100.00%
src/.../__init__.py                           0       0  100.00%
src/.../model.py                             22       6  72.73%   26-31
tests/__init__.py                             0       0  100.00%
tests/test_model.py                          20       1  95.00%   28
TOTAL                                        42       7  83.33%
```
Would be interesting if there were any easy way to parse this table, e.g. to get the TOTAL/Cover value of 83.33%.

**Comment by aconrad** [comment]
Hi @gro1m,

No easy way to parse the text output, it wasn't designed to be consumed directly (best is using the Python library to get the coverage into).

Otherwise, did you try to use shell commands to extract what you care from the output? E.g.

```bash
pycobertura show coverage.xml | grep TOTAL | awk '{print $4}'
```

**Comment by aconrad** [comment]
Another way would be to use Python, as suggested in my previous comment:

```bash
$ python3 -c "import pycobertura; print(pycobertura.Cobertura('tests/cobertura.xml').line_rate())"
0.9
```

Here you would get the line rate, not the formatted percentage.

**Comment by aconrad** [comment]
Closing this thread for now, feel free to reopen if you need to discuss further.

**Comment by gro1m** [comment]
Hi @aconrad 
I am not sure it is so hard to implement as you could operate on the formatted_lines list on https://github.com/aconrad/pycobertura/blob/31ded1efc70f514df804664b74ccc8cd91143815/pycobertura/reporters.py#L79, https://github.com/aconrad/pycobertura/blob/31ded1efc70f514df804664b74ccc8cd91143815/pycobertura/reporters.py#L107, https://github.com/aconrad/pycobertura/blob/31ded1efc70f514df804664b74ccc8cd91143815/pycobertura/reporters.py#L230,
https://github.com/aconrad/pycobertura/blob/31ded1efc70f514df804664b74ccc8cd91143815/pycobertura/reporters.py#L288, respectively.
If it fits the design/purpose of the library is another question, but I think it is not too hard from an implementation perspective :)

With respect to reopening the issue, I think the following rule applies:
- you cannot re-open your own issues if a repo collaborator closed them 
(source: https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github)

**Comment by gro1m** [comment]
For the sake of reading headers it would be nicer though to use the dictionary example from [tabulate](https://pypi.org/project/tabulate/) to have the headers as keys:
```python
>>> print(tabulate({"Name": ["Alice", "Bob"],
...                 "Age": [24, 19]}, headers="keys"))
  Age  Name
-----  ------
   24  Alice
   19  Bob
```

**Comment by aconrad** [comment]
I think I misunderstood your original request. What do you want to achieve? What is your question?

Reopening.

**Comment by gro1m** [comment]
Hi @aconrad 
I do not necessarily want to parse the text output of the `pycobertura show` command, but have a way to retrieve the individual values displayed in that matrix. And what I tried to explain above is that this information is pretty much already present in the `generate` function's `formatted_lines` list variable.

**Comment by gro1m** [comment]
Maybe this helps as well to clarify.
Doing an editable install of this repo via ` pip install -e git+https://github.com/aconrad/pycobertura#egg=pycobertura` and adding a print statement for the formatted lines and using https://github.com/aconrad/pycobertura/blob/master/tests/cobertura.xml in 
```python
pycobertura show cobertura.xml
```
yields:
```bash
formatted_lines = [FileRowMissed(filename='Main.java', total_statements=11, total_misses=0, line_rate='100.00%', missed_lines=''), FileRowMissed(filename='search/BinarySearch.java', total_statements=12, total_misses=1, line_rate='91.67%', missed_lines='24'), FileRowMissed(filename='search/ISortedArraySearch.java', total_statements=0, total_misses=0, line_rate='100.00%', missed_lines=''), FileRowMissed(filename='search/LinearSearch.java', total_statements=7, total_misses=2, line_rate='71.43%', missed_lines='19-24'), FileRowMissed(filename='TOTAL', total_statements=30, total_misses=3, line_rate='90.00%', missed_lines='')]

Filename                          Stmts    Miss  Cover    Missing
------------------------------  -------  ------  -------  ---------
Main.java                            11       0  100.00%
search/BinarySearch.java             12       1  91.67%   24
search/ISortedArraySearch.java        0       0  100.00%
search/LinearSearch.java              7       2  71.43%   19-24
TOTAL                                30       3  90.00%
```
so the information is pretty much there and maybe a slight more convenient data structure for `formatted_lines` could be used, but I think to have a cli command to display a single value based on this should be possible to do.

**Comment by aconrad** [comment]
I'm still unclear about the ask. In one of your comments you say:

> [...] have a way to retrieve the individual values displayed in that matrix.

What "way" are you thinking about? Is it from the command line (CLI) or programmatically (in Python)? And it sounds you want to cherry-pick what you get back in the output, is that correct? If it's from the CLI then would you need additional switches? Would something like this work?:

```bash
$ pycobertura show coverage.xml --show-coverage-rate --path="search/LinearSearch.java"
71.43%
```

... or if it where for the TOTAL row:

```bash
$ pycobertura show coverage.xml --show-coverage-rate --total
90.00%
```

We could imagine that `--path` and `--total` would be mutually exclusive. Or could we allow multiple values to be outputted a the same time? Then what would the output look like?

Is that getting closer to what you are looking for?

**Comment by gro1m** [comment]
Hi @aconrad 

Yes, the commands you show are pretty much exactly those that I am looking for.

If it were sensible to keep the `show` in there as you do not output the whole file content might be debatable - probably easier to keep like that (could though lead to breaking changes in future if the naming convention were to be changed) and *a detail* with regards to functionality.

With respect to the return value, I think it is ok to output a singular value.
If you would return a list, the user probably would need to make use of associative arrays (https://linuxize.com/post/bash-arrays/) - at least the only bash datastructure I know of - that seem to me rather inconvenient to handle and require quite some extra code. 
Therefore, the only reasonable way I see to support multiple values - which indeed would be a bit more general - is to output a string with a delimiter (e.g. ,) between different elements that would make further processing if need be probably quite easy.

**Comment by aconrad** [comment]
Thanks @gro1m.

> If it were sensible to keep the show in there as you do not output the whole file content might be debatable - probably easier to keep like that (could though lead to breaking changes in future if the naming convention were to be changed) and a detail with regards to functionality.

I don't understand what you mean by that sentence, can you please clarify?

Either way, now that I understand a little better what your request is, I'm now thinking about whether this is a feature I'd like to include in pycobertura. It's essentially a subset of what the `show` command already provides and this information is also accessible via the Python API so someone like you could write a thin wrapper command to extract what is needed. Alternatively, using bash to cut/split the output of `show` is not ideal but it gets the job done. 🤷

If we were to introduce a CLI command to extract single values from the coverage, I'd want it to be generic enough so someone could extract any metrics (coverage rate, lines missed, etc.), and ideally, in one pass of they needed to extract, say, two values at once. They could run the command twice targeting 2 different metrics but it feels wasteful to reparse the same coverage report multiple times when all the data could be made available the first time.

All this leads me to think of another idea: return a JSON output with all the metrics data for the user to cherry-pick from. That would mean introducing a new coverage reporter, e.g. `JsonReporter` (would inherit `Reporter`) to return a JSON string. For example:

```bash
$ pycobertura show --json coverage.xml
{
  "total": {
    "filename": "TOTAL",
    "statements": 30,
    "missed": 3,
    "percentage": "90.00%",
    "rate": 0.9,
    "missing": []
  },
  "files": [
    {
      "filename": "Main.java",
      "statements": 11,
      "missed": 0,
      "percentage": "100.00%",
      "rate": 1.0,
      "missing": []
    },
    ...
    {
      "filename": "search/LinearSearch.java",
      "statements": 7,
      "missed": 2,
      "percentage": "71.43%",
      "rate": 0.7143,
      "missing": [19, 20, 21, 22, 23, 24]
    }
  ]
}
```

The output could then be used by the caller to extract information using a JSON parser instead of having to fiddle with cut/split or the Python API. For example, one could use the popular JSON parser CLI tool `jq`:

```bash
$ pycobertura show --json coverage.xml | jq -r '.total.percentage'
90.00%
```

I think introducing a `JsonReporter` makes the most sense to me. It's flexible and is a ubiquitous format that can be consumed in various scenarios (from the CLI, from the Python API). I'd be happy to review a pull request if you are interested. I'm happy to discuss further implementation details if you wish.

What do you think?

**Comment by gro1m** [comment]
Hi @aconrad 

I certainly think it would make sense to implement a json output, so I could try to come up with a PR for that if you think that'd be sensible.

Nonetheless, I think it would still be nice to have either a `pycobertura show coverage.xml --query '.total.percentage'` or a `pycobertura parse coverage.xml --value 'total.percentage'`:
1. With growing security concerns the number of installed packages is minimized, so that even a standard package like `jq` may actually not be installed in a base docker image.
2. The amount of values to query for for is a finite and known as in-built into this library (at least if my understanding of the library implementation is correct).
In the context on how to handle multiple values in parsing, the answer could be like `jq`:
```bash
$ pycobertura show --json coverage.xml | jq -r '.total | .statements, .percentage'
30
90.00%
```
By default `jq` seems to use  new-line formatting for displaying the output and comma-delimiter, but could also be tab-separated (`@tsv`) or maybe even newline-separated, see also https://stackoverflow.com/a/68664471/9698518.

Specifically, I tested this with the following two examples:
```bash
$ echo '{"total": {"filename": "TOTAL","statements": 30,"missed": 3,"percentage": "90.00%","rate": 0.9,"missing": []}}' | jq -r '.total| [.statements, .percentage]'
[
  30,
  "90.00%"
]

$ echo '{"total": {"filename": "TOTAL","statements": 30,"missed": 3,"percentage": "90.00%","rate": 0.9,"missing": []}}' | jq -r '.total| .statements, .percentage'
30
90.00%
```

What do you think?

**Comment by aconrad** [comment]
Thanks for your message @gro1m.

As of now, let's implement the JSON reporters so users can start extracting the values they care about using their own JSON parser. I think this would be a good first step.

The CLI command should be:

```bash
pycobertura show --format json coverage.xml
```

(note that we already support `--format html` so that could be a good starting point)

As for having `pycobertura show` query for specific values, this is not a feature I am convinced we should implement right now. Implementing a `--query` command that parses a string such as `'.total.percentage'` seems like the type of work I don't want to get into for now. It might start simple but users might ask to support more complex use-cases, thus adding complexity to the syntax, which is not something I feel comfortable supporting. Does that make sense?

**Comment by aconrad** [comment]
Oops, closed by accident.

**Comment by gro1m** [comment]
Ok, I can try that, but before I start I will need to ask you about the Python versions `pycobertura` shall support.
You are testing Python 3.5,3.6,3.7 and the specification is a bit different here: https://github.com/gro1m/pycobertura/blob/master/setup.py#L42-L46.

At the same point regarding end of life of Python versions, looking at the https://devguide.python.org/#status-of-python-branches, Python 3.7 onwards should be supported. I have Python 3.8 installed and no running tests, which I think is not so nice :)

And before I would start implementing the JSON reporter, I would try to do some refactoring, but that could possibly mean there could be breaking changes (i.e. no backwards compatibility and the need to do a major release). Therefore, I would like to ask you to tell me which Python versions shall be supported by `pycobertura` at this point in time and what you think about the inconsistencies above? - especially I do not think that Python 2 should be supported anymore.

**Comment by aconrad** [comment]
We don't support 2.x. I guess the `setup.py` hasn't been updated after this decision.

Right now on Travis CI we build for 3.5, 3.6, and 3.7. I think we should support newer versions of Python, too. And I'm happy to only support 3.7 and up.

Are you saying that pycobertura under 3.8 doesn't work? Oops, we should certainly submit a separate PR to fix support for that (and future versions).

**Comment by gro1m** [comment]
Hi @aconrad 
Thanks for your reply.

> Are you saying that pycobertura under 3.8 doesn't work? Oops, we should certainly submit a separate PR to fix support for that (and future versions).

No, it is only the tests are restricted to Python versions 3.5, 3.6, 3.7, i.e. the tox command returns:
```bash
$ tox
py35 create: /<MY $HOME>/vscode-projects/pycobertura/.tox/py35
ERROR: InterpreterNotFound: python3.5
py36 create: /<MY $HOME>/vscode-projects/pycobertura/.tox/py36
ERROR: InterpreterNotFound: python3.6
py37 create: /<MY $HOME>/vscode-projects/pycobertura/.tox/py37
ERROR: InterpreterNotFound: python3.7
pep8 installed: flake8==4.0.1,mccabe==0.6.1,pycodestyle==2.8.0,pyflakes==2.4.0
pep8 run-test-pre: PYTHONHASHSEED='3167248157'
pep8 run-test: commands[0] | pip install flake8
Requirement already satisfied: flake8 in ./.tox/pep8/lib/python3.9/site-packages (4.0.1)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in ./.tox/pep8/lib/python3.9/site-packages (from flake8) (2.4.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./.tox/pep8/lib/python3.9/site-packages (from flake8) (0.6.1)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in ./.tox/pep8/lib/python3.9/site-packages (from flake8) (2.8.0)
pep8 run-test: commands[1] | flake8 pycobertura/
black installed: black==21.12b0,click==8.0.3,mypy-extensions==0.4.3,pathspec==0.9.0,platformdirs==2.4.1,tomli==1.2.3,typing_extensions==4.0.1
black run-test-pre: PYTHONHASHSEED='3167248157'
black run-test: commands[0] | pip install black
Requirement already satisfied: black in ./.tox/black/lib/python3.9/site-packages (21.12b0)
Requirement already satisfied: click>=7.1.2 in ./.tox/black/lib/python3.9/site-packages (from black) (8.0.3)
Requirement already satisfied: tomli<2.0.0,>=0.2.6 in ./.tox/black/lib/python3.9/site-packages (from black) (1.2.3)
Requirement already satisfied: platformdirs>=2 in ./.tox/black/lib/python3.9/site-packages (from black) (2.4.1)
Requirement already satisfied: mypy-extensions>=0.4.3 in ./.tox/black/lib/python3.9/site-packages (from black) (0.4.3)
Requirement already satisfied: pathspec<1,>=0.9.0 in ./.tox/black/lib/python3.9/site-packages (from black) (0.9.0)
Requirement already satisfied: typing-extensions>=3.10.0.0 in ./.tox/black/lib/python3.9/site-packages (from black) (4.0.1)
black run-test: commands[1] | black --check pycobertura/
All done! ✨ 🍰 ✨
8 files would be left unchanged.
___________________________________________________ summary ____________________________________________________
ERROR:  py35: InterpreterNotFound: python3.5
ERROR:  py36: InterpreterNotFound: python3.6
ERROR:  py37: InterpreterNotFound: python3.7
  pep8: commands succeeded
  black: commands succeeded
```

But then I will go ahead and will first submit a refactoring PR that supports Python 3.7 upwards which you can then review. And I also realized just now that there is a `CHANGES.md` that states that Python 2 support was dropped, so that's great :)

**Comment by aconrad** [comment]
`InterpreterNotFound` means that it didn't find the right python version on your computer.

We can see green builds on Travis:

https://app.travis-ci.com/github/aconrad/pycobertura
