### ISSUE TITLE
@aconrad it looks like you forgot to `git push` when you tagged the latest release :)

### ISSUE THREAD

**Issue by 1ace** [aconrad/pycobertura#121]
The github page for 07bf866dbdafb0ea3f39d866a6b1ab94f13ae224 says:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

@aconrad it looks like you forgot to `git push` the commit when you tagged the latest release :slightly_smiling_face:

**Comment by aconrad** [comment]
Oh whoops! 😬

Unfortunately I don't have access to a computer in the next few days. I'll double check when I do.

I'm curious to know what happened because I usually use a script to make new releases, which I expect to do a `git push` in the process... 🤔

Thanks for letting me know!

**Comment by aconrad** [comment]
@1ace I think I pushed what might've been missing. Can you double-check on your side?

**Comment by aconrad** [comment]
Closing this for now.

**Comment by 1ace** [comment]
Yes, I can confirm, the `master` branch now contains the 2.1.0 commit :+1:

Thanks!
