### ISSUE TITLE
Get an understanding of what is needed for the 3.0.0 release

### ISSUE THREAD

**Issue by gro1m** [aconrad/pycobertura#134]
Hi @aconrad 
I think would be interesting what needs to be in for the 3.0.0 release.
It would also be interesting to see if some of the Issues could be closed and what the current PRs are doing to have a well-defined state of the repo when releasing the next major version.

**Comment by aconrad** [comment]
All your PRs were merged so happy to work on a release. The issue about the XML being different between py37 and py38 would be nice to figure out since this release focuses on dropping py2. But maybe we can address that later.

**Comment by aconrad** [comment]
> * tests for reporters as well (I only did the CLI tests)

CLI tests indirectly over them already, so definitely a nice-to-have but not a blocker for 3.0.

> * resolve inconsistency between Python versions

Yes, the fact that py37 and py38 are different bothers me, and I'd love for us to get that figured out before a 3.0 release.

> * clean-up the PRs (the one you opened is one line) and the issues we have (I close those that will be addressed or will not be done), because new issues could arise with the new release. Also there are issues that are quite old and we should check if there are still relevant or not.

I closed PR #75 which was no longer relevant. Then there's #109. The feature request is about grouping outputs on a per-directory and introduces a YAML output that you just introduced. But either way, I don't think that would be a blocker for 3.0.

> * some mentioned they want to regex match files
> * merging xml files was a topic

I also don't think any new feature should be a blocker. Those can come in as 3.1 if that's something we decide we want to have.

In general, I'd say most of the issues have stalled. I should start from the oldest issues and close them one by one if they aren't relevant anymore, or ask people to reopen the issues if they still care about them.

**Comment by aconrad** [comment]
pycobertura 3.0.0 was released
