### ISSUE TITLE
Pycobertura diff command only supports text and html output format?

### ISSUE THREAD

**Issue by chixiangzhou** [aconrad/pycobertura#143]
Problem:
I was trying to generate a yaml output using pycobertura diff command. But it threw an error and implies that only text and html are supported. See the screenshot below:
![image](https://user-images.githubusercontent.com/24377651/162094459-41dff4be-2d4b-415d-a188-021635f92b1c.png)

The README shows yaml, json, and other format are also supported.

The version of pycobertura I'm currently using is 2.1.0. See the screenshot below:
![image](https://user-images.githubusercontent.com/24377651/162094900-ff5ae4ba-2c70-4044-a1d4-8e54c709b7af.png)

Did I miss anything here?

**Comment by aconrad** [comment]
We haven't released that feature yet. It will be part of v3. You'd have to use the master branch instead of the python package in the meantime.

**Comment by chixiangzhou** [comment]
I see. Do you know when will that feature be released?

**Comment by aconrad** [comment]
@gro1m has been helping a lot lately, we're trying to go through some of the issues and see if we can fix some low-hanging fruit and add new features. But on my side, time is my main constraint, life keeps me pretty busy and yet I try to respond to incoming requests in a somewhat timely manner. 😅

I should do a better job at identifying which of those are meant to be in 3.0. Maybe we should use a "3.0" label or something so we can better keep track of our progress...

The changes you suggested in #142 would be nice additions, too. If you want to help with those (e.g. consider that previously non-exist files are "100%" covered, or show before/after columns in the summary table). We can start by capturing this work in separate tickets and then we can discuss how to move forward. Thoughts?

**Comment by chixiangzhou** [comment]
> The changes you suggested in https://github.com/aconrad/pycobertura/issues/142 would be nice additions, too. If you want to help with those (e.g. consider that previously non-exist files are "100%" covered, or show before/after columns in the summary table). We can start by capturing this work in separate tickets and then we can discuss how to move forward. Thoughts?

Sure. I'll capture this work in a separate ticket. Like i mentioned in #142 , I'll try my best to help with this enhancement, but it might take a bit of time for me. Just wanted to set the right expectation here. 😅

**Comment by chixiangzhou** [comment]
I filed two tickets #144 and #145 to capture the work.

**Comment by chixiangzhou** [comment]
Closing this ticket #143, as I think you answered my question.
