### ISSUE TITLE
[Feature Request] Do a delta on previously non-exist files

### ISSUE THREAD

**Issue by chixiangzhou** [aconrad/pycobertura#144]
Adding a new file is a common use case in software development. Developers might be interested in how many lines are covered in the new file, and what is the delta.

Currently, pycobertura diff report considers that previously non-exist files cannot do a delta, and marks the Column **Cover** as "-".  IMO, it would make more sense to consider that previously non-exist files are "100%" covered, and do a delta after the new file is introduced. Thus, the diff coverage can be shown in the Column **Cover.**

**Comment by aconrad** [comment]
This should've been addressed with https://github.com/aconrad/pycobertura/pull/155

**Comment by aconrad** [comment]
pycobertura-3.0.0 was released, I hope this release addresses this issue. Please reopen if not.
