### ISSUE TITLE
Pycobertura requires git to install the Markdown feature

### ISSUE THREAD

**Issue by ZaneH** [aconrad/pycobertura#156]
When installing pycobertura with:

```
pycobertura>=2.1.0
```

in my requirements.txt, I appear to be missing functionality (specifically the Markdown format option.)

If I specify the branch as such:

```
git+https://github.com/aconrad/pycobertura.git@master
```

It comes with the features I expect from pycobertura and just works!

The issue is that we don't want to add git as a dependency for 1 other dependency. Is there a way to update the PyPi version or specify the branch in requirements.txt without needing git?

Thanks!

**Comment by aconrad** [comment]
Hi @ZaneH, the markdown features haven't been released yet which explains why it's only available through git. We had a few things we wanted to finish before making a new release. I'll take a look at what is left to make a new release, likely later in the week.

**Comment by ZaneH** [comment]
Oh wow perfect timing

Thank you!

**Comment by aconrad** [comment]
pycobertura 3.0.0 was released
