### ISSUE TITLE
How to install without pip and without admin rights

### ISSUE THREAD

**Issue by nbauma109** [aconrad/pycobertura#179]
I want to use this project but I don't have pip installed, nor do I have the rights to install it

Can't I just run python /path/to/script.py ?

**Comment by aconrad** [comment]
Hi @nbauma109, I suggest you look up how to install a Python package manually, [see example](https://stackoverflow.com/questions/13270877/how-to-manually-install-a-pypi-module-without-pip-easy-install). I hope this helps.
