### ISSUE TITLE
Non-zero exit status if coverage goes down

### ISSUE THREAD

**Issue by aconrad** [aconrad/pycobertura#19]
I would like to return a non-zero exit status if the coverage goes down:

``` bash
$ pycobertura diff coverage.xml coverage.worse.xml > /dev/null
$ echo $?
1
```

**Comment by lemongao** [comment]
Hi,

Can you explain more about the meaning of the exit code?

2: coverage worsened (implies 3)  ---Does this mean Cover Rate (Cover Column) decrease? 
3: not all changes are covered ---Does this mean if there is any new line uncovered. return 3 as exit code ?

**Comment by aconrad** [comment]
Coverage worsened (exit code 2) means that you effectively left the code base in a worse coverage state than you have found it. It means that the overall number of uncovered lines has increased, plain and simple.

Exit code 3 means that you have reduced the overall number of uncovered lines in your code base (yay!) but if you follow the philosophy that "all changes should be tested" then it means that as long as you have changes that haven't been tested then it will fail the build. This can happen if you submit a patch that removes more uncovered lines than it adds, and yet, the lines that you have added are not completely covered.

For example, let's say you have a total of 100 uncovered lines (your coverage technical debt) and you submit a patch that deletes 10 uncovered lines and adds 5 new lines (not yet tested). It means that you end up in a state where the number of uncovered lines dropped to 95 (100-10+5) and you effectively made the code base _less_ uncovered. Congrats! As long as pycobertura sees that the 5 new lines are not covered, it will use exit code 3 (which you might decide is an acceptable trade-off). Once you decide to cover these 5 new lines with new tests, then it will quit with exit code 0 and everyone will be very happy.

Exit code 2 is considered "bad" in the sense that code coverage has worsened. Exit code 3 is not as bad in the sense that, yes, you improve the code coverage of your code base, but you can still do a better job at testing all of the changes you are introducing.
