### ISSUE TITLE
fail on uncovered lines or uncovered changes

### ISSUE THREAD

**Issue by aconrad** [aconrad/pycobertura#50]
Add the ability to fail on uncovered lines or uncovered changes.
- uncovered lines: if the total number of uncovered lines rose, then fail the build. This would be the default and the "strict" version.
- uncovered changes: if a change is not tested (red lines in the diff), then fail the build. Ideally these changes should be covered but if the overall uncovered lines is lower, then the build could already be loosely considered of "better quality".

Maybe we could have a `--fail-on-uncovered` option (or just `--fail-on`) that could take `lines` or `changes`:

```
pycobertura diff --fail-on-uncovered=changes ...
pycobertura diff --fail-on-uncovered=lines ...
```

**Comment by lemongao** [comment]
HI, can we set the fail-on criteria, eg uncovered changes  line percent?

**Comment by aconrad** [comment]
@lemongao I don't plan on failing the build based on coverage rate (percentage) because the rate can down even when your changes are valid. I don't believe the percentage should be used as a metric to measure whether the code coverage of a code base becomes better or worse. See https://github.com/aconrad/pycobertura/blob/master/README.md#why-is-the-number-of-uncovered-lines-used-as-the-metric-to-check-if-code-coverage-worsened-rather-than-the-line-rate

**Comment by aconrad** [comment]
I'm going to close this issue because this is currently handled by the exit status code of pycobertura. See https://github.com/aconrad/pycobertura/blob/master/README.md#diff-exit-codes
