### ISSUE TITLE
Multiple coverage xmls

### ISSUE THREAD

**Issue by juandiegopalomino** [aconrad/pycobertura#87]
I was wondering if it's possible for this package to work when the coverage data is split among several xmls which are for tests of the same codebase

**Comment by aconrad** [comment]
Currently pycobertura only knows how to parse one XML file at a time.

I know that tools exist to combine multiple XML coverage reports together but I have never done it myself. For example https://coverage.readthedocs.io/en/coverage-4.2/cmd.html#combining-data-files
